#!/bin/sh

. /Users/akhoucha/Documents/akhoucha/Applications/mampstack-7.1.13-0/scripts/setenv.sh

exec /Users/akhoucha/Documents/akhoucha/Applications/mampstack-7.1.13-0/git/libexec/git-core/.git-remote-ftp.bin  "$@"
